### ISSUE TITLE
Exception when loading script files

### ISSUE THREAD

**Issue by c0d3z3r0** [allfro/BurpKit#10] opened 2016-01-11 10:19 UTC
I get an exception when trying to load one of the example script files in BurpKitty.

Java version: tried 8u51, 8u65, 8u66

Warning: context class loader for JFX thread returned null.
java.lang.NoClassDefFoundError: com/sun/javafx/Utils
    at org.fxmisc.richtext.StyledTextArea.replaceText(StyledTextArea.java:696)
    at org.fxmisc.richtext.EditActions.clear(EditActions.java:95)
    at com.redcanari.ui.JavaScriptEditor.lambda$createMenuBar$109(JavaScriptEditor.java:170)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$null$294(EmbeddedScene.java:256)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$295(EmbeddedScene.java:244)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.Utils
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 38 more

**Comment by allfro** [comment] 2016-01-11 15:31
Hi there,

What OS is this running on?

**Comment by b1ack0wl** [comment] 2016-01-11 17:27
I'm having the same issue with the BurpScript IDE. After some googling I found this - http://stackoverflow.com/questions/32440763/cant-seem-to-run-javafx-project-in-eclipse

"The problem is that the class com.sun.javafx.Utils was moved to com.sun.javafx.util.Utils package in update 60 of Java 8." 

Mac OSX 10.10.5 
JDK 8u66

**Comment by b1ack0wl** [comment] 2016-01-11 19:52
I may have found the issue. I'm re-compiling now and I'll let you know if replacing the ControlFX with the latest one works since they redid the JavaFX import.

**Comment by allfro** [comment] 2016-01-11 19:53
This is a known issue with the code editor control. I haven't had a chance
to look at it yet but I believe you will need to recompile with the latest
version of the RichTextFX control.

**Comment by b1ack0wl** [comment] 2016-01-26 16:23
I've been re-compiling but still getting the same issue. I would like to help out with this issue but I may be doing something wrong. Any guidance?

**Comment by allfro** [comment] 2016-01-26 17:23
I'll take a look at it today. Not sure what the issue is because I am
unable to reproduce it so far. What version of the JDK are you using? Is it
OpenJDK or Oracle?

**Comment by b1ack0wl** [comment] 2016-01-26 19:19
I'm using Oracle (jdk-8u65-macosx-x64) I can try updating the latest JDK - http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by allfro** [comment] 2016-01-26 19:45
This issue appears to be fixed in RichTextFX Snapshot-1.0.0 as specified
here: https://github.com/TomasMikula/RichTextFX/issues/155. Recompiling
BurpKit with the latest snapshot of RichTextFX should work. I will try that
later on today. See if that helps you as well.

**Comment by b1ack0wl** [comment] 2016-01-26 23:07
I'll try that now. Thanks!!

**Comment by allfro** [comment] 2016-01-26 23:20
I'm working on it still. ControlsFX needs to be updated to the latest as
well. They're all using the same class so it's causing other NPEs. I've
fixed the first issue so it may work in the latest pull requests. There are
still some other issues like dialog boxes that don't work.

**Comment by allfro** [comment] 2016-01-27 04:37
This issue should be fixed with release [v1.03-pre](https://github.com/allfro/BurpKit/releases/tag/v1.03-pre). Please let me know if it works for you and I will close this issue.

**Comment by allfro** [comment] 2016-01-29 12:09
Please reopen this issue if you are still experiencing the same problem with the latest release.

**Closed as completed by allfro** 2016-01-29 12:09 UTC
Labels: bug

**Comment by b1ack0wl** [comment] 2016-01-29 15:10
The issue is now gone. Thanks for helping out!
